// Generated by gencpp from file me326_locobot_example/PixtoPoint.msg
// DO NOT EDIT!


#ifndef ME326_LOCOBOT_EXAMPLE_MESSAGE_PIXTOPOINT_H
#define ME326_LOCOBOT_EXAMPLE_MESSAGE_PIXTOPOINT_H

#include <ros/service_traits.h>


#include <me326_locobot_example/PixtoPointRequest.h>
#include <me326_locobot_example/PixtoPointResponse.h>


namespace me326_locobot_example
{

struct PixtoPoint
{

typedef PixtoPointRequest Request;
typedef PixtoPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PixtoPoint
} // namespace me326_locobot_example


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::me326_locobot_example::PixtoPoint > {
  static const char* value()
  {
    return "453b790c7c72ce0c0a5e253a59f6dc48";
  }

  static const char* value(const ::me326_locobot_example::PixtoPoint&) { return value(); }
};

template<>
struct DataType< ::me326_locobot_example::PixtoPoint > {
  static const char* value()
  {
    return "me326_locobot_example/PixtoPoint";
  }

  static const char* value(const ::me326_locobot_example::PixtoPoint&) { return value(); }
};


// service_traits::MD5Sum< ::me326_locobot_example::PixtoPointRequest> should match
// service_traits::MD5Sum< ::me326_locobot_example::PixtoPoint >
template<>
struct MD5Sum< ::me326_locobot_example::PixtoPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::me326_locobot_example::PixtoPoint >::value();
  }
  static const char* value(const ::me326_locobot_example::PixtoPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::me326_locobot_example::PixtoPointRequest> should match
// service_traits::DataType< ::me326_locobot_example::PixtoPoint >
template<>
struct DataType< ::me326_locobot_example::PixtoPointRequest>
{
  static const char* value()
  {
    return DataType< ::me326_locobot_example::PixtoPoint >::value();
  }
  static const char* value(const ::me326_locobot_example::PixtoPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::me326_locobot_example::PixtoPointResponse> should match
// service_traits::MD5Sum< ::me326_locobot_example::PixtoPoint >
template<>
struct MD5Sum< ::me326_locobot_example::PixtoPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::me326_locobot_example::PixtoPoint >::value();
  }
  static const char* value(const ::me326_locobot_example::PixtoPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::me326_locobot_example::PixtoPointResponse> should match
// service_traits::DataType< ::me326_locobot_example::PixtoPoint >
template<>
struct DataType< ::me326_locobot_example::PixtoPointResponse>
{
  static const char* value()
  {
    return DataType< ::me326_locobot_example::PixtoPoint >::value();
  }
  static const char* value(const ::me326_locobot_example::PixtoPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ME326_LOCOBOT_EXAMPLE_MESSAGE_PIXTOPOINT_H
